{% set version = "2.0.9" %}

package:
  name: bob.ip.base
  version: {{ version }}

source:
  fn: bob.ip.base-{{ version }}.zip
  url: https://pypi.python.org/packages/source/b/bob.ip.base/bob.ip.base-{{ version }}.zip
  md5: 5b91c13d0a5e9b354d576139fb1f6c2d

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools
    - matplotlib
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.sp
    - bob.io.base
    - bob.math
    - vlfeat
    - boost 1.60.*
    - cmake
    - pkg-config

  run:
    - python
    - matplotlib
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.sp
    - bob.io.base
    - bob.math
    - vlfeat
    - boost 1.60.*

test:
  commands:
    - nosetests -sv bob.ip.base

  imports:
    - bob
    - bob.ip
    - bob.ip.base
    - bob.ip.base.test

  requires:
    - nose

about:
  home: http://github.com/bioidiap/bob.ip.base
  license: Modified BSD License (3-clause)
  summary: Basic Image Processing Utilities for Bob

extra:
  recipe-maintainers:
    - 183amir
