travis:
  secure:
    BINSTAR_TOKEN: l15g5EkWKBYjLqGdhTPyuAx4SRL4mXWteIMukxif7VRaJtogmmoLF7QxD8Nh2nJp9cHnJHcrLm1e4VVsQTLvYg4t2FdFyrLFCkoQAhBVkv6NZWyKCzk3QOW+WAJg2lV1KUriAiNrOZEh4k/wr6+4f0kdezRDAC33TqYL93AHPHOAO2FyZb0EPXYlNTnjFE8iABt0/C6juNkuTd1Mmy1wsHumZ/bdZAuzY4MVxXCo7ExQi5onfHwn/Lm88wfZR7BGJ+zFLrX0H0DYmVXRGwoPVaKXlOsJQUIYasODtimh4mn9bgc0OCR54KzX25o7sQLsiunmcIcE10vbLHrmt04VXKgxsfGa+KFQMv1d6Z4WR5+7SjPM2qH1KSrtHY9Y+3wQI9N2TQCEHvY5sKh4g6Emv2AQOpHQRJZX8qwQC/bfJAFkTBaOauzQieJzZ9RcRV+bMHC7DAVMP6erEHGn3o14J84e0bWvMWbRqhKRIZULDLyycQN7hYjkCp32Yb43Wzf6c2BDzdBxKkOeIFiE8jEnTMLpy/+ntaCZF03TPK28WLOKOgJzOmsUbcxUBo9GLjOCG4fRDzpxAoccpF8pKeDn10jOwQua7wwDeHfUh7IH0CkIPbjkhfS9mbI+ZKVPOakpp451yGzzYTEjZ8cuIa4sX2Wx7w+HcL+M2NHne5KGepE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
